
name:
    local-use
server:
 port: 7846
eureka:
    instance:
      hostname: localhost
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      server-url:
        defaultZone: http://localhost:8761/eureka
